# Generated by Django 5.1.7 on 2025-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_categories', '0010_alter_hobbycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbycategory',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
