# Generated by Django 5.1.7 on 2025-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_categories', '0012_hobbycategory_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbycategory',
            name='cover',
            field=models.ImageField(upload_to='category_covers/', verbose_name='Обложка'),
        ),
    ]
