# Generated by Django 5.1.7 on 2025-03-20 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_categories', '0014_human'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['name'], 'verbose_name': 'Человека', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='human',
            name='category',
        ),
        migrations.AddField(
            model_name='human',
            name='current_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_members', to='hobby_categories.hobbycategory', verbose_name='Текущая категория'),
        ),
    ]
