# Generated by Django 5.1.7 on 2025-03-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_categories', '0015_alter_human_options_remove_human_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='current_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_members', to='hobby_categories.hobbycategory', verbose_name='Текущая категория'),
        ),
    ]
