# Generated by Django 5.1.7 on 2025-03-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_categories', '0016_alter_human_current_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
