# Generated by Django 5.1.7 on 2025-03-20 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_categories', '0017_delete_human'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbycategory',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='hobby_categories', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
